### ISSUE TITLE
Failed to create snapshot content with error cannot find CSI PersistentVolumeSource for volume

### ISSUE THREAD

**Issue by nivGandhi** [backube/snapscheduler#283]
**Describe the bug**

I am getting below error while running in k8.  out of 200 pvc 80% are create snapshot 20% getting below error

**Failed to create snapshot content with error cannot find CSI
      PersistentVolumeSource for volume**

**Steps to reproduce**

1. Install the snapscheduler
2. Create Volume Snapshot class
`apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
deletionPolicy: Delete
driver: disk.csi.azure.com
parameters:
  incremental: 'true'
`
3. Schedule the job
4. `apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: pvcdaily
spec:
  retention:
    maxCount: 1
  schedule: 0/5 * * * *
  snapshotTemplate:
    labels:
      mylabel: pvcbackup
    snapshotClassName: csi-azuredisk-vsc
`
**Expected behavior**

 it will create backup for all pvc
**Actual results**

80% success 20% failed 

**Additional context**

**Comment by JohnStrunk** [comment]
Where do you see the error? This looks like an error that would be reported by the CSI driver, perhaps as an event on the VolumeSnapshot object?

(assuming the above...)
SnapScheduler creates the VolumeSnapshot object, but it's up to the other controllers in the cluster to actually respond to that. Since you're getting snapshots for most of your volumes, all the components are probably present and working.

I'd suggest taking a look at the PVCs that you're having trouble with... Is it always the same ones? Is there something different about those? (Are they using a different StorageClass?)

**Comment by JohnStrunk** [comment]
It sounds like SnapScheduler is working properly--- You're getting the VolumeSnapshot objects as expected, but they aren't being bound to VolumeSnapshotContent objects.

Some things to try:
- Manually creating VolumeSnapshot objects for the PVCs that you are having trouble with. If this works, then perhaps there's a rate-limiting issue
- Compare the PVC, PV, and VolumeSnapshot objects that work w/ those that don't. There must be some difference.
- Take a look at the logs from the CSI driver. Perhaps it will show a more detailed error message.

**Comment by nivGandhi** [comment]
> It sounds like SnapScheduler is working properly--- You're getting the VolumeSnapshot objects as expected, but they aren't being bound to VolumeSnapshotContent objects.
> 
> Some things to try:
> 
> * Manually creating VolumeSnapshot objects for the PVCs that you are having trouble with. If this works, then perhaps there's a rate-limiting issue
> * Compare the PVC, PV, and VolumeSnapshot objects that work w/ those that don't. There must be some difference.
> * Take a look at the logs from the CSI driver. Perhaps it will show a more detailed error message.

**Yes, you are correct, while taking snapshot backup manually, it is not working.** I will debug the issues and update you.

you can close the bug.

**Comment by nivGandhi** [comment]
HI John,

Let me know if you have any idea. If disk was provisioned-by: kubernetes.io/azure-disk then it is not working and if disk is provisioned-by: disk.csi.azure.com it is working.

do you have any idea how to migrate the disk?

Thanks in advance.

**Comment by JohnStrunk** [comment]
The `kubernetes.io/azure-disk` is the old in-tree driver, whereas `disk.csi.azure.com` is the (new) CSI driver. Snapshots are only supported for CSI drivers, so that's why it's not working.

All the in-tree drivers are being deprecated in favor of CSI--- each has its own timeline.

Fortunately, Azure Disk is supporting volume migration, allowing you to convert to the CSI driver. It looks like migration was [declared stable in 1.24](https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk-csi-migration). I'm not sure what you need to do, but hopefully this at least gives you a starting point. Once you get the PVs switched over, I'd expect snapshots to start working.

**Comment by nivGandhi** [comment]
Hi John,

Just want to quick check. is there any way to tag the snapshot while taking the backup using [snapscheduler](https://github.com/backube/snapscheduler).

Thanks in advance.

**Comment by JohnStrunk** [comment]
The `snapshotTemplate` allows specifying labels. See: https://backube.github.io/snapscheduler/usage.html

**Comment by JohnStrunk** [comment]
Feel free to open an issue for it w/ the labels you'd like to have. PRs welcome also.
